### ISSUE TITLE
En smukkere og optimeret version af kalenderen

### ISSUE THREAD

**Issue by oscarschack** [alternativetsunge/udkast#11]
Ideen med kalenderen er god da den er smart med facebook integreringen, den er dog ikke super smuk og mangler muligheden for at tilføje et event uden en facebook begivenhed.

Dette burde kunne tilføjes på et senere tidspunkt

**Comment by jakobvarmose** [comment]
I stedet for kalenderen skal vi måske blot linke til vores facebook-sider/grupper indtil videre?

**Comment by oscarschack** [comment]
Jeg synes vi skal prøve denne kalender af, den virker ret lækkert og da vi ikke behøver acceptere events, da folk bare skal invitere os og så hopper det op
