### ISSUE TITLE
tilføj banner igen

### ISSUE THREAD

**Issue by oscarschack** [alternativetsunge/udkast#20]
![banner](https://user-images.githubusercontent.com/25135372/34116334-9a28a868-e418-11e7-9bc3-fbeea59ae489.png)
Vores banner i højre hjørne er med en forkert og ikke så pæn font! Den må derfor gerne opdateres til dette banner i stedet for

**Comment by jakobvarmose** [comment]
Så vidt jeg kan se er det det samme logo, men blot en nedskaleret udgave.

**Comment by oscarschack** [comment]
Fonten er anderledes og afstanden mellem bogstaverne også større :)

**Comment by oscarschack** [comment]
Og så er logoet også opdateret en smule
