### ISSUE TITLE
Klares inden vi går live: Fjern adresse og nummer i footer

### ISSUE THREAD

**Issue by oscarschack** [alternativetsunge/udkast#3]
Disse numre er ikke ÅU's men Alternativets

**Comment by jakobvarmose** [comment]
Det er rigtigt, men på den anden side er det også smart hvis folk kan ringe til os. Så måske skal vi beholde nummeret, men blot skrive at det er til Alternativet?

**Comment by oscarschack** [comment]
Det kunne man godt, men addressen skal væk, da vi jo ikke har en fast adresse
