### ISSUE TITLE
"Hvem er vi"

### ISSUE THREAD

**Issue by oscarschack** [alternativetsunge/udkast#5]
Lave en "hvem er vi" under "om os" side med en hel masse billeder og en tekst om ÅU i.

Denne tekst er ved at blive skrevet og vil blive lagt op her når vi får den.

**Comment by oscarschack** [comment]
Alternativets Unge (ÅU) er den officielle ungdomsafdeling for Alternativet.

Vi har tre hovedformål:

At styrke unges demokratiske stemme både lokalt, regionalt, nationalt og internationalt.
At flere unge tager del i og ansvar for en seriøs bæredygtig omstilling.
At Alternativet som bevægelse og politisk platform bliver et samlingspunkt for alle generationer.
Her er alle velkomne!

I Alternativets Unge har vi hverken landegrænser eller aldersgrænser. Det betyder, at du – uanset om du er 10 eller 110 år, eller om du er fra Danmark eller Nepal – kan være med til at skabe en forskel både lokalt og globalt sammen med Alternativets Unge!

Vi er overalt!

På trods af, at vi først lige er blevet stiftet, kan man allerede finde os rigtig mange steder i landet! Hvis du ønsker at være en del af bevægelsen men ikke kan finde din afdeling, bedes du skrive til unge@alternativet.dk, så vil vi meget gerne hjælpe dig med at komme i kontakt med din respektive lokal- eller storkredsafdeling!

Vi er helt grønne!

Alternativets Unge blev stiftet den 10. december. Det betyder, at vi kæmper en brav kamp for at få foreningen op at køre. Så hvis der er noget, du ikke kan finde – ja, så er det derfor. Det vil meget snart være muligt at melde sig ind i foreningen, og vi får også snart vores egen hjemmeside op at stå! I mellemtiden vil vi opfordre dig til at holde dig opdateret på vores facebookside; Alternativets Unge.

Har du spørgsmål, så må du endelig bare hive fat i os eller dukke op til et arrangement. Vi ses! 🙂

**Comment by oscarschack** [comment]
http://alternativet.dk/har-alternativet-et-ungdomsparti/

**Comment by jakobvarmose** [comment]
Det er nu sat ind på forsiden. Dog uden det sidste afsnit da det ikke er korrekt længere.

Men vi kunne godt bruge nogle flere billeder.
