### ISSUE TITLE
Laves inden vi går live: Sted med LTG dokumenter

### ISSUE THREAD

**Issue by oscarschack** [alternativetsunge/udkast#7]
Lav et sted med dagordner og referater. Dette skal være et sted der linker til landstovholdergruppens drev. Linker kommer snart

**Comment by oscarschack** [comment]
https://drive.google.com/open?id=0B5hXplati0n7SDZqM2Y3NEtudVk

**Comment by jakobvarmose** [comment]
Måske som et underpunkt til "Om os" der hedder "Dokumenter"?

**Comment by oscarschack** [comment]
God ide!
